In [139]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [140]:
df = pd.read_csv(r"E:\playground-series-s4e1\train.csv")
df.head()

id  CustomerId         Surname  CreditScore Geography Gender   Age  Tenure  \
0   0    15674932  Okwudilichukwu          668    France   Male  33.0       3   
1   1    15749177   Okwudiliolisa          627    France   Male  33.0       1   
2   2    15694510           Hsueh          678    France   Male  40.0      10   
3   3    15741417             Kao          581    France   Male  34.0       2   
4   4    15766172       Chiemenam          716     Spain   Male  33.0       5   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              2        1.0             0.0        181449.97   
1       0.00              2        1.0             1.0         49503.50   
2       0.00              2        1.0             0.0        184866.69   
3  148882.54              1        1.0             1.0         84560.88   
4       0.00              2        1.0             1.0         15068.83   

   Exited  
0       0  
1       0  
2       0  
3       0  
4       0

In [141]:
vf = pd.read_csv(r"E:\playground-series-s4e1\test.csv")
vf.head()

id  CustomerId    Surname  CreditScore Geography  Gender   Age  Tenure  \
0  165034    15773898   Lucchese          586    France  Female  23.0       2   
1  165035    15782418       Nott          683    France  Female  46.0       2   
2  165036    15807120         K?          656    France  Female  34.0       7   
3  165037    15808905  O'Donnell          681    France    Male  36.0       8   
4  165038    15607314    Higgins          752   Germany    Male  38.0      10   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0       0.00              2        0.0             1.0        160976.75  
1       0.00              1        1.0             0.0         72549.27  
2       0.00              2        1.0             0.0        138882.09  
3       0.00              1        1.0             0.0        113931.57  
4  121263.62              1        1.0             0.0        139431.00

In [143]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [144]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [145]:
x = vf.iloc[:, 3:].values
x[:, 2] = le.transform(x[:, 2])
x[0]

array([586, 'France', 0, 23.0, 2, 0.0, 2, 0.0, 1.0, 160976.75],
      dtype=object)

In [146]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1.0, 0.0, 181449.97],
       [1.0, 0.0, 0.0, ..., 1.0, 1.0, 49503.5],
       [1.0, 0.0, 0.0, ..., 1.0, 0.0, 184866.69],
       ...,
       [1.0, 0.0, 0.0, ..., 1.0, 1.0, 127429.56],
       [0.0, 0.0, 1.0, ..., 0.0, 1.0, 71173.03],
       [1.0, 0.0, 0.0, ..., 1.0, 0.0, 61581.79]], dtype=object)

In [148]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = ct.fit_transform(x)
x[0]

array([1.0, 0.0, 0.0, 586, 0, 23.0, 2, 0.0, 2, 0.0, 1.0, 160976.75],
      dtype=object)

In [150]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [151]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [152]:
ann = tf.keras.models.Sequential()

In [153]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [154]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

In [155]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [156]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [157]:
ann.fit(X_train, y_train, batch_size=32, epochs=20)

Epoch 1/20
4126/4126 [==============================] - 5s 1ms/step - loss: 0.3844 - accuracy: 0.8362
Epoch 2/20
4126/4126 [==============================] - 4s 1ms/step - loss: 0.3335 - accuracy: 0.8597
Epoch 3/20
4126/4126 [==============================] - 4s 950us/step - loss: 0.3293 - accuracy: 0.8622
Epoch 4/20
4126/4126 [==============================] - 5s 1ms/step - loss: 0.3279 - accuracy: 0.8634
Epoch 5/20
4126/4126 [==============================] - 4s 974us/step - loss: 0.3274 - accuracy: 0.8638
Epoch 6/20
4126/4126 [==============================] - 4s 930us/step - loss: 0.3271 - accuracy: 0.8638
Epoch 7/20
4126/4126 [==============================] - 4s 1ms/step - loss: 0.3268 - accuracy: 0.8638
Epoch 8/20
4126/4126 [==============================] - 4s 949us/step - loss: 0.3267 - accuracy: 0.8637
Epoch 9/20
4126/4126 [==============================] - 4s 1ms/step - loss: 0.3265 - accuracy: 0.8634
Epoch 10/20
4126/4126 [==============================] - 4s 1ms/step - los

In [159]:
x = x.astype('float32')
y_pre = ann.predict(x)
y_pred = []
for i in y_pre:
    if i > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

3439/3439 [==============================] - 3s 883us/step


In [86]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8638470627442664
[[24732  1356]
 [ 3138  3781]]


In [160]:
fg = pd.DataFrame()
fg["id"] = vf["id"]
fg["Exited"] = y_pred

In [162]:
fg.to_csv("sample 3")