In [48]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [49]:
df = pd.read_csv("E:\Deep learning UDEMY\P16-Artificial-Neural-Networks\Part 1 - Artificial Neural Networks\Churn_Modelling.csv")

In [50]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [51]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1:].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [52]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1, 2])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
X


array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [54]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# sc1 = StandardScaler()
# X_train = sc.fit_transform(X_train)
# # y_train = sc1.fit_transform(y_train)

In [55]:
ann = tf.keras.models.Sequential()

In [56]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

In [57]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

In [58]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

In [59]:
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

In [60]:
ann.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss=tf.keras.losses.BinaryCrossentropy(),
    metrics=[
        tf.keras.metrics.BinaryAccuracy(),
        tf.keras.metrics.FalseNegatives(),
    ],
)

In [61]:
X_train = X_train.astype(float)
y_train = y_train.astype(float)

In [62]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 629.8215 - binary_accuracy: 0.6676 - false_negatives_3: 1246.0000
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 36.5158 - binary_accuracy: 0.6875 - false_negatives_3: 1320.0000
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 41.0824 - binary_accuracy: 0.6926 - false_negatives_3: 1295.0000
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 34.1471 - binary_accuracy: 0.6864 - false_negatives_3: 1302.0000
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 44.1866 - binary_accuracy: 0.6930 - false_negatives_3: 1275.0000
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 36.8913 - binary_accuracy: 0.6824 - false_negatives_3: 1289.0000
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 44.7964 - binary_accuracy: 0.6860 - false_negatives_3: 1282.0000
Epoch 8/100
250/250

In [67]:
ann.predict(ct.transform([[600, "France", "Male", 40, 3, 60000, 2, 1, 1, 50000]]).astype(float)) 

1/1 [==============================] - 0s 34ms/step


array([[0.8147604]], dtype=float32)

In [72]:
y_pred = ann.predict(X_test.astype(float))
y_pred = y_pred > 0.5

63/63 [==============================] - 0s 1ms/step


In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[689 918]
 [ 78 315]]
0.502


In [71]:
y_pred

array([[9.9997991e-01],
       [1.0648024e-05],
       [1.9560504e-01],
       ...,
       [3.0977451e-03],
       [5.2744931e-10],
       [9.9999940e-01]], dtype=float32)