In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
df = pd.read_csv(r"E:\playground-series-s4e1\train.csv")
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values
X

array([[668, 'France', 'Male', ..., 1.0, 0.0, 181449.97],
       [627, 'France', 'Male', ..., 1.0, 1.0, 49503.5],
       [678, 'France', 'Male', ..., 1.0, 0.0, 184866.69],
       ...,
       [565, 'France', 'Male', ..., 1.0, 1.0, 127429.56],
       [554, 'Spain', 'Female', ..., 0.0, 1.0, 71173.03],
       [850, 'France', 'Male', ..., 1.0, 0.0, 61581.79]], dtype=object)

In [4]:
df.head()

id  CustomerId         Surname  CreditScore Geography Gender   Age  Tenure  \
0   0    15674932  Okwudilichukwu          668    France   Male  33.0       3   
1   1    15749177   Okwudiliolisa          627    France   Male  33.0       1   
2   2    15694510           Hsueh          678    France   Male  40.0      10   
3   3    15741417             Kao          581    France   Male  34.0       2   
4   4    15766172       Chiemenam          716     Spain   Male  33.0       5   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              2        1.0             0.0        181449.97   
1       0.00              2        1.0             1.0         49503.50   
2       0.00              2        1.0             0.0        184866.69   
3  148882.54              1        1.0             1.0         84560.88   
4       0.00              2        1.0             1.0         15068.83   

   Exited  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
X[0]

array([1.0, 0.0, 0.0, 668, 1, 33.0, 3, 0.0, 2, 1.0, 0.0, 181449.97],
      dtype=object)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
ann = tf.keras.models.Sequential()

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))#first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))#second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))#output layer

In [14]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [15]:
ann.fit(X_train, y_train, batch_size=32, epochs=20)

Epoch 1/20


4126/4126 [==============================] - 5s 1ms/step - loss: 0.4107 - accuracy: 0.8272
Epoch 2/20
4126/4126 [==============================] - 4s 971us/step - loss: 0.3576 - accuracy: 0.8463
Epoch 3/20
4126/4126 [==============================] - 4s 940us/step - loss: 0.3377 - accuracy: 0.8556
Epoch 4/20
4126/4126 [==============================] - 4s 989us/step - loss: 0.3309 - accuracy: 0.8617
Epoch 5/20
4126/4126 [==============================] - 4s 945us/step - loss: 0.3285 - accuracy: 0.8624
Epoch 6/20
4126/4126 [==============================] - 4s 1ms/step - loss: 0.3273 - accuracy: 0.8629
Epoch 7/20
4126/4126 [==============================] - 4s 1ms/step - loss: 0.3266 - accuracy: 0.8627
Epoch 8/20
4126/4126 [==============================] - 4s 957us/step - loss: 0.3263 - accuracy: 0.8634
Epoch 9/20
4126/4126 [==============================] - 4s 1ms/step - loss: 0.3259 - accuracy: 0.8633
Epoch 10/20
4126/4126 [==============================] - 5s 1ms/step -

In [58]:
single = [[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]

In [59]:
single = sc.transform(single)

In [62]:
ann.predict(single)

1/1 [==============================] - 0s 24ms/step


array([[0.02838937]], dtype=float32)

In [75]:
y_pre = ann.predict(X_test)
y_pred = []
for i in y_pre:
    if i > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

63/63 [==============================] - 0s 1ms/step


In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1502   93]
 [ 197  208]]
0.855
