In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv(r"E:\BlackClover\Machine Learning-A-Z-Codes-Datasets (1)\Machine Learning A-Z (Codes and Datasets)\Part 2 - Regression\Section 5 - Multiple Linear Regression\Python\50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [-1])], remainder="passthrough")
X = ct.fit_transform(X)

In [6]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)


LinearRegression()

In [9]:
y_pred = regressor.predict(X_test)
y_pred

array([126362.87908251,  84608.45383643,  99677.49425157,  46357.46068583,
       128750.48288496,  50912.41741904, 109741.35032702, 100643.24281644,
        97599.27574601, 113097.42524437])

In [10]:
y_test

array([134307.35,  81005.76,  99937.59,  64926.08, 125370.37,  35673.41,
       105733.54, 107404.34,  97427.84, 122776.86])

In [18]:
result = pd.DataFrame()

In [20]:
result["actual value"] = y_test
result["predicted value"] = y_pred
result["difference value"] = y_diff

In [21]:
print(result)

   actual value  predicted value  difference value
0     134307.35    126362.879083      -7944.470917
1      81005.76     84608.453836       3602.693836
2      99937.59     99677.494252       -260.095748
3      64926.08     46357.460686     -18568.619314
4     125370.37    128750.482885       3380.112885
5      35673.41     50912.417419      15239.007419
6     105733.54    109741.350327       4007.810327
7     107404.34    100643.242816      -6761.097184
8      97427.84     97599.275746        171.435746
9     122776.86    113097.425244      -9679.434756
