READ, WRITE AND APPEND FILE

In [1]:
with open("te.txt", "r") as file:
    with open("copy.txt", "w") as f:
        value = file.read()
        for i in file.read():
            f.write(i)

In [2]:
with open("copy.txt", "w") as file:
    file.write("hi this is Harish")

PANDAS

In [4]:
import pandas as pd

In [3]:
df = pd.read_csv(r"E:\Dataset\anime\Anime.csv")

In [6]:
df.head()

Rank                                               Name  \
0     1  Demon Slayer: Kimetsu no Yaiba - Entertainment...   
1     2                     Fruits Basket the Final Season   
2     3                                    Mo Dao Zu Shi 3   
3     4                   Fullmetal Alchemist: Brotherhood   
4     5                Attack on Titan 3rd Season: Part II   

                                     Japanese_name   Type  Episodes  \
0                    Kimetsu no Yaiba: Yuukaku-hen  TV          NaN   
1                          Fruits Basket the Final  TV         13.0   
2                       The Founder of Diabolism 3  Web        12.0   
3   Hagane no Renkinjutsushi: Full Metal Alchemist  TV         64.0   
4             Shingeki no Kyojin Season 3: Part II  TV         10.0   

              Studio Release_season  \
0           ufotable          Fall    
1  TMS Entertainment         Spring   
2   B.C MAY PICTURES            NaN   
3              Bones         Spring   
4         WIT Studio         Spring   

                                                Tags  Rating  Release_year  \
0  Action, Adventure, Fantasy, Shounen, Demons, H...    4.60        2021.0   
1  Drama, Fantasy, Romance, Shoujo, Animal Transf...    4.60        2021.0   
2  Fantasy, Ancient China, Chinese Animation, Cul...    4.58        2021.0   
3  Action, Adventure, Drama, Fantasy, Mystery, Sh...    4.58        2009.0   
4  Action, Fantasy, Horror, Shounen, Dark Fantasy...    4.57        2019.0   

   End_year                                        Description  \
0       NaN  'Tanjiro and his friends accompany the Hashira...   
1       NaN                  'The final arc of Fruits Basket.'   
2       NaN               'The third season of Mo Dao Zu Shi.'   
3    2010.0  "The foundation of alchemy is based on the law...   
4       NaN  'The battle to retake Wall Maria begins now! W...   

                                     Content_Warning  \
0                                  Explicit Violence   
1  Emotional Abuse,, Mature Themes,, Physical Abu...   
2                                                NaN   
3  Animal Abuse,, Mature Themes,, Violence,, Dome...   
4                    Cannibalism,, Explicit Violence   

                                       Related_Mange  \
0                     Demon Slayer: Kimetsu no Yaiba   
1               Fruits Basket, Fruits Basket Another   
2  Grandmaster of Demonic Cultivation: Mo Dao Zu ...   
3  Fullmetal Alchemist, Fullmetal Alchemist (Ligh...   
4  Attack on Titan, Attack on Titan: End of the W...   

                                       Related_anime  \
0  Demon Slayer: Kimetsu no Yaiba, Demon Slayer: ...   
1  Fruits Basket 1st Season, Fruits Basket 2nd Se...   
2                   Mo Dao Zu Shi 2, Mo Dao Zu Shi Q   
3  Fullmetal Alchemist: Brotherhood Specials, Ful...   
4  Attack on Titan, Attack on Titan 2nd Season, A...   

                                        Voice_actors  \
0  Inosuke Hashibira : Yoshitsugu Matsuoka, Nezuk...   
1  Akito Sohma : Maaya Sakamoto, Kyo Sohma : Yuum...   
2  Lan Wangji, Wei Wuxian, Jiang Cheng, Jin Guang...   
3  Alphonse Elric : Rie Kugimiya, Edward Elric : ...   
4  Armin Arlelt : Marina Inoue, Eren Jaeger : Yuu...   

                                               staff  
0  Koyoharu Gotouge : Original Creator, Haruo Sot...  
1  Natsuki Takaya : Original Creator, Yoshihide I...  
2  Mo Xiang Tong Xiu : Original Creator, Xiong Ke...  
3  Hiromu Arakawa : Original Creator, Yasuhiro Ir...  
4  Hajime Isayama : Original Creator, Tetsurou Ar...

In [26]:
df["Type"].unique()

array(['TV   ', 'Web  ', 'Movie', 'OVA  ', 'Music', 'TV Sp', 'DVD S',
       'Other'], dtype=object)

In [9]:
 k = df["Studio"].unique()
len(k)

746

In [12]:
df["Type"].size

18495

In [24]:
df["Episodes"].max()

800.0

In [2]:
di = {"Student":["David", "Samuel", "Terry", "Evan"], 
      "Age":[27, 24, 22, 32], 
      "Country":["UK", "Canada", "China", "USA"], 
      "Course":["Python", "Data Structures", "Machine learning", "web development"], 
      "Marks":[85, 72, 89, 76]}
df1 = pd.DataFrame(di)
df1

NameError: name 'pd' is not defined

In [5]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv"
df = pd.read_csv(filename)

In [6]:
df.head()

Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

In [7]:
df["Length"]

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object

In [8]:
q = df["Rating"]
q

0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5
Name: Rating, dtype: float64

In [10]:
q = df[["Released", "Artist"]]
q

Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

In [11]:
df.iloc[2, 3]

'0:42:49'

In [13]:
new_index=['a','b','c','d','e','f','g','h']

NUMPY

In [14]:
import numpy as np

In [15]:
li = [0,1,2,3,4,5]
na = np.array(li)

In [16]:
na

array([0, 1, 2, 3, 4, 5])

In [17]:
na.size

6

In [19]:
u = np.array([1, 0])
v = np.array([1, 1])
z = []
print(u + v)

[2 1]


In [20]:
for i, j in zip(u, v):
    z.append(i + j)
z

[2, 1]

In [22]:
print(np.array([1, 2]) * np.array([3, 4]))

[3 8]


In [23]:
print(np.dot(u, v))

1


In [24]:
print(v + 1)

[2 2]


In [27]:
np.linspace(-2, 2, 9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [30]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
print(type(b))
print(b.dtype)

<class 'numpy.ndarray'>
float64


In [32]:
a = np.array([10, 2, 30, 40,50])

a[1] = 20
a

array([10, 20, 30, 40, 50])

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:7:2])

[1 3 5 7]


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[0:8:2])

[1 3 5 7]
